### ISSUE TITLE
Why `escapeSequence()` treat characters whose charCodes is under 256 as ascii, not utf-16?

### ISSUE THREAD

**Issue by yichung279** [aemkei/jsfuck#115]
In `escapeSequence()`,characters whose charCodes is under 256 will turn into ascii code.
However, it works well if we treat it as utf-16. Both `"\141"` and `"\u0061"`  represent `"a"`.
https://github.com/aemkei/jsfuck/blob/94c38357375e5009ebeb97fcc6934aaea482b210/jsfuck.js#L232-L240

Is 
```   
if (cc < 256) { 
     return '\\' + cc.toString(8); 
} 
```
a necessary statement?

**Comment by yichung279** [comment]
If it is not necessary, I remove it in #116

**Comment by frobinsonj** [comment]
Although both result in working jsfuck, this was added as the resulting jsfuck is shorter when representing ASCII chars using the ISO-8859-1 escape notation (`\XXX (where XXX is 1–3 octal digits; range of 0–377)`). See Pull request #93 and #88 :)

**Comment by hazzik** [comment]
This was done to optimize the length of resulting code

**Comment by yichung279** [comment]
Oh, I see. What a great work!
