### ISSUE TITLE
Use array 'at' method instead of array 'filter' method

### ISSUE THREAD

**Issue by maeema** [aemkei/jsfuck#125]
While Internet Explorer is now dead, and the 'at' method is compatible with all other browsers, I think using the 'at' to eval the code can reduce the size of the compilation results a little bit.

that means:
 * Function =>  `[]["at"]` instead of `[]["filter"]`.
 * eval => `[]["at"]["constructor"]( CODE )()` instead of `[]["filter"]["constructor"]( CODE )()`.
 * window => `[]["at"]["constructor"]("return this")()` instead of `[]["filter"]["constructor"]("return this")()`

**Comment by hazzik** [comment]
Duplicate of #119

**Comment by hazzik** [comment]
Also, it is not 'filter' anymore it is 'flat'

**Comment by maeema** [comment]
The discussion will continue on #119.
