### ISSUE TITLE
A better way of getting `A`

### ISSUE THREAD

**Issue by 49b** [aemkei/jsfuck#128]
Running a function in `Array.prototype` and converting its output to string results in a string with the letter A.

Before:

`(+[]+[]["constructor"])[10]`

`(+[]+[][([][(![]+[])[+[]]+(![]+[])[!+[]+!+[]]+(![]+[])[+!+[]]+(!![]+[])[+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[][(![]+[])[+[]]+(![]+[])[!+[]+!+[]]+(![]+[])[+!+[]]+(!![]+[])[+[]]])[+!+[]+[+[]]]+([][[]]+[])[+!+[]]+(![]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[+[]]+([][(![]+[])[+[]]+(![]+[])[!+[]+!+[]]+(![]+[])[+!+[]]+(!![]+[])[+[]]]+[])[!+[]+!+[]+!+[]]+(!![]+[])[+[]]+(!![]+[][(![]+[])[+[]]+(![]+[])[!+[]+!+[]]+(![]+[])[+!+[]]+(!![]+[])[+[]]])[+!+[]+[+[]]]+(!![]+[])[+!+[]]])[+!+[]+[+[]]]`

---

After:

`([]["entries"]()+[])[8]`

`([][(![]+[])[!+[]+!+[]+!+[]+!+[]]+([][[]]+[])[+!+[]]+(!![]+[])[+[]]+(!![]+[])[+!+[]]+([][[]]+[])[!+[]+!+[]+!+[]+!+[]+!+[]]+(![]+[])[!+[]+!+[]+!+[]+!+[]]+(![]+[])[!+[]+!+[]+!+[]]]()+[])[!+[]+!+[]+!+[]+!+[]+!+[]+!+[]+!+[]+!+[]]`

**Comment by hazzik** [comment]
This should be even smaller:

```js
(+[]+[]["entries"])[10]
```

**Comment by hazzik** [comment]
Actually, this is how it is already done in the master:

https://github.com/aemkei/jsfuck/blob/1f02651e98da1c13aef76d609755a2568a1aa6b4/jsfuck.js#L52

It was done in #110

I think this can be closed.

**Comment by 49b** [comment]
oops, sorry. I thought it wasn't done like that because the website is not up to date.
