### ISSUE TITLE
Uppercase characters

### ISSUE THREAD

**Issue by shibby360** [aemkei/jsfuck#134]
`.toUpperCase` can be used for other uppercase letters
 
H : `(+(101))["to"+String["name"]](21)[1]["toUpperCase"]()`

J : `([]["entries"]()+"")[3]["toUpperCase"]()`

K : `(+(20))["to"+String["name"]](21)["toUpperCase"]()`

L : `(false+"")[2]["toUpperCase"]()`

... and so forth

**Comment by hazzik** [comment]
Yes, true. And this is how it was a long time ago, however this will at least double the current lengths for the characters.
![image](https://github.com/aemkei/jsfuck/assets/144791/5941893c-5bbf-4456-b535-ca0258dfb7b8)

**Comment by shibby360** [comment]
Oh ok I didn't realize
