### ISSUE TITLE
Infinity Question

### ISSUE THREAD

**Issue by HellCracks** [aemkei/jsfuck#37]
Why are you using: `'+(+!+[]+(!+[]+[])[!+[]+!+[]+!+[]]+[+!+[]]+[+[]]+[+[]]+[+[]])'` for infinity instead of  `'1/!1'?`
Won't both do the same?

Sorry, but for the question, but I'm more or less a javascript newbie.

**Comment by rajparmar** [comment]
I'm guessing because "1" isn't part of the 6 characters that make up the set used for jsFuck?

**Comment by aemkei** [comment]
It is more that `/` is not part of the character set.
