### ISSUE TITLE
Encoding simple IIFE seems to fail

### ISSUE THREAD

**Issue by finetype** [aemkei/jsfuck#49]
when I try to encode `(function(){return 1})()`, and copy and paste the output and run it in my console, that code returns 'undefined' instead of 1. (That said, if instead of `return 1` I put `alert(1)`, it does work.)

**Comment by hazzik** [comment]
You need to encode 'return (function(){return 1})()'

When you select 'eval' option, it is already IIF style function

**Comment by aemkei** [comment]
Thanks @hazzik !
