### ISSUE TITLE
Looks like ( is being encoded as "v" and ) as "a"

### ISSUE THREAD

**Issue by kthompson** [aemkei/jsfuck#62]
Looks like when you use "(" or ")" they are being incorrectly encoded as "v" and "a" respectively.

**Comment by hazzik** [comment]
In which exact browser?

**Comment by kthompson** [comment]
Not sure it was over two years ago. Probably chrome. I don't have any vested interest in seeing this fixed though. Close it if you want. Cool project though 🥂
